# Generated by Django 4.2.23 on 2025-09-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='customer_logos/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='testimonial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
