# Generated by Django 4.2.23 on 2025-09-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_customer_logo_customer_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
